apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vilas-app-1
  namespace: default
spec:
  interval: 1m
  path: "./fluxcd/repositories/vilas-app-1/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: vilas-app-1
